;;; -*- lexical-binding: t -*-
(defun my-cut ()
  (interactive)
  (if (use-region-p)
      (kill-region (region-beginning) (region-end))
    (kill-whole-line)))

(defun my-copy ()
  (interactive)
  (if (use-region-p)
      (copy-region-as-kill (region-beginning) (region-end))
    (progn (kill-ring-save (line-beginning-position) (line-beginning-position 2)))))

(defun my-move-line-up ()
  (interactive)
  (transpose-lines 1)
  (forward-line -2))

(defun my-move-line-down ()
  (interactive)
  (forward-line 1)
  (transpose-lines 1)
  (forward-line -1))

(defun my-copy-line-and-move-down ()
  (interactive)
  (duplicate-line)
  (next-line 1))

(defun my-delete-whole-line-no-kill ()
  (interactive)
  (delete-region (line-beginning-position) (line-beginning-position 2)))

(defun my-kill ()
  (interactive)
  (when (and (buffer-file-name)
             (file-exists-p (buffer-file-name))
             (buffer-modified-p))
    (save-buffer))
  (kill-current-buffer)
  (when (= (count-windows) 2)
    (delete-window)))

(defun my-downcase-dwim ()
  (interactive)
  (if (use-region-p)
      (downcase-region (region-beginning) (region-end))
    (call-interactively #'downcase-word)))

(defun my-upcase-dwim ()
  (interactive)
  (if (use-region-p)
      (upcase-region (region-beginning) (region-end))
    (call-interactively #'upcase-word)))

(defun my-home-dired ()
  (interactive)
  (dired "~"))

(defun my-switch-to-project-root ()
  (interactive)
  (if-let* ((proj (project-current)))
      (dired (project-root proj))
    (dired default-directory)))

(defun my-surround-word (char)
  "Wrap word at point or active region with CHAR."
  (interactive "cWrap char: ")
  (let ((beg (if (use-region-p) (region-beginning)
               (car (bounds-of-thing-at-point 'word))))
        (end (if (use-region-p) (region-end)
               (cdr (bounds-of-thing-at-point 'word)))))
    (when (and beg end)
      (save-excursion
        (goto-char end) (insert char)
        (goto-char beg) (insert char)))))

(defun my-surround-replace (char)
  (interactive "cReplace surrounding chars with: ")
  (when-let ((bounds (bounds-of-thing-at-point 'word)))
    (save-excursion
      (goto-char (car bounds))
      (when (search-backward-regexp "[^[:space:]]" (line-beginning-position) t)
        (delete-char 1) (insert char))
      (goto-char (cdr bounds))
      (when (search-forward-regexp "[^[:space:]]" (line-end-position) t)
        (delete-char -1) (insert char)))))

(defun my-surround-replace-pair (old-char new-char)
  (interactive "cWrap char? \ncReplace surrounding chars with: ")
  (when-let ((bounds (bounds-of-thing-at-point 'word)))
    (save-excursion
      (goto-char (car bounds))
      (when (search-backward (string old-char) (line-beginning-position) t)
        (delete-char 1)
        (insert (string new-char)))
      (goto-char (cdr bounds))
      (when (search-forward (string old-char) (line-end-position) t)
        (delete-char -1)
        (insert (string new-char))))))

(defun my-replace (from to &optional delimited start end)
  (interactive
   (let ((beg (if (use-region-p) (region-beginning) (point-min)))
         (end (if (use-region-p) (region-end)       (point-max))))
     (list (read-string "Replace: ")
           (read-string "With: ")
           nil beg end)))
  (replace-string from to delimited start end))

(defun my-split-and-switch (direction)
  (let ((buf (read-buffer
              "Switch to buffer: "
              (other-buffer (current-buffer) t))))
    (pcase direction
      ('right (select-window (split-window-right)))
      ('below (select-window (split-window-below)))
      ('left  (split-window-right))
      ('above (split-window-below)))
    (switch-to-buffer buf)))

(defun my-split-right-and-switch ()  (interactive) (my-split-and-switch 'right))
(defun my-split-left-and-switch  ()  (interactive) (my-split-and-switch 'left))
(defun my-split-below-and-switch ()  (interactive) (my-split-and-switch 'below))
(defun my-split-above-and-switch ()  (interactive) (my-split-and-switch 'above))


(defun scroll-half-screen-up ()
  "向下滚动半屏（文字向上移动）。"
  (interactive)
  (scroll-up (/ (window-body-height) 2)))

(defun scroll-half-screen-down ()
  "向上滚动半屏（文字向下移动）。"
  (interactive)
  (scroll-down (/ (window-body-height) 2)))

;; 绑定快捷键（可以根据个人习惯修改）

(keymap-global-set "C-c C-d"  #'scroll-half-screen-up)
(keymap-global-set "C-c C-u"  #'scroll-half-screen-down)


(keymap-global-set "<escape>" #'keyboard-escape-quit)
(keymap-global-set "C-!" #'my-replace)
(keymap-global-set "C-c o f" #'my-split-right-and-switch)
(keymap-global-set "C-c o b" #'my-split-left-and-switch)
(keymap-global-set "C-c o n" #'my-split-below-and-switch)
(keymap-global-set "C-c o p" #'my-split-above-and-switch)
(keymap-global-set "C-c o l" #'my-split-right-and-switch)
(keymap-global-set "C-c o h" #'my-split-left-and-switch)
(keymap-global-set "C-c o j" #'my-split-below-and-switch)
(keymap-global-set "C-c o k" #'my-split-above-and-switch)
(keymap-global-set "C-c w r" #'my-surround-replace)
(keymap-global-set "C-c w R" #'my-surround-replace-pair)
(keymap-global-set "C-c w w" #'my-surround-word)
(keymap-global-set "C-c C-r" #'my-switch-to-project-root)
(keymap-global-set "C-c C-j" #'project-dired)
(keymap-global-set "M-w" #'my-copy)
(keymap-global-set "C-w" #'my-cut)
(keymap-global-set "C-x k" #'my-kill)
(keymap-global-set "C-x C-k" #'kill-buffer)
(keymap-global-set "C-x C-d" #'my-delete-whole-line-no-kill)
(keymap-global-set "C-," #'my-copy-line-and-move-down)
(keymap-global-set "C-~" #'my-home-dired)
(keymap-global-set "C-'" #'imenu)
(keymap-global-set "C-1" #'scroll-up-command)
(keymap-global-set "C-2" #'scroll-down-command)
(keymap-global-set "C-3" #'recenter-top-bottom)
(keymap-global-set "S-<tab>" #'indent-rigidly-left-to-tab-stop)
(keymap-global-set "C-<tab>" #'next-buffer)
(keymap-global-set "C-S-<tab>" #'bs-cycle-previous)
(keymap-global-set "C-a" #'back-to-indentation)
(keymap-global-set "C-M-a" #'move-beginning-of-line)
(keymap-global-set "C-v" #'yank)
(keymap-global-set "C-z" #'undo)
(keymap-global-set "C-S-z" #'undo-redo)
(keymap-global-set "C-M-k" #'windmove-up)
(keymap-global-set "C-M-j" #'windmove-down)
(keymap-global-set "C-M-h" #'windmove-left)
(keymap-global-set "C-M-l" #'windmove-right)
(keymap-global-set "M-<f11>" #'toggle-frame-fullscreen)
(keymap-global-set "M-S-l" #'shrink-window-horizontally)
(keymap-global-set "M-S-h" #'enlarge-window-horizontally)
(keymap-global-set "M-S-j" #'shrink-window)
(keymap-global-set "M-S-k" #'enlarge-window)
(keymap-global-set "M-l" #'my-downcase-dwim)
(keymap-global-set "M-r" #'my-upcase-dwim)
(keymap-global-set "M-k" #'my-move-line-up)
(keymap-global-set "M-j" #'my-move-line-down)

(provide 'init-keybind)
