# ~/.profile: executed by Bourne-compatible login shells.

export PS1="\[\e[0;31m\]\D{%F %T}|\[\e[1;33m\]\u|\[\e[36m\]\w$"
export HOMEBREW_NO_AUTO_UPDATE=true

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

SYSTEM=`uname -s`
if [ $SYSTEM == "Darwin" ]; then
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
fi
