#!/bin/bash
export PS1="\[\e[0;31m\]\D{%F %T}|\[\e[1;33m\]\u|\[\e[36m\]\w$"

#添加git的自动完成命令功能
if [ -f ~/.path.bash ]; then
source ~/.path.bash
fi

[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
. /opt/local/etc/profile.d/bash_completion.sh
fi

#添加git的自动完成命令功能
if [ -f ~/.git-completion.bash ]; then
source ~/.git-completion.bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function


if [ -f ~/.aliasrc ]; then
source ~/.aliasrc
fi

ulimit -c unlimited

#if [ -f ~/.fzf.bash ]; then
#    source ~/.fzf.bash
#fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export EDITOR=vim

