# ~/.profile: executed by Bourne-compatible login shells.

export PS1="\[\e[0;31m\]\D{%F %T}|\[\e[1;33m\]\u|\[\e[36m\]\w$"
export HOMEBREW_NO_AUTO_UPDATE=true
export BASH_SILENCE_DEPRECATION_WARNING=1

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

SYSTEM=`uname -s`
if [ $SYSTEM == "Darwin" ]; then
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

unset MAILCHECK

# Added by Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"

. "$HOME/.local/bin/env"

# Hermes Agent — ensure ~/.local/bin is on PATH
export PATH="$HOME/.local/bin:$PATH"

[ ! -f "$HOME/.x-cmd.root/X" ] || . "$HOME/.x-cmd.root/X" # boot up x-cmd.
export PATH="$PATH:$HOME/.local/bin"

# Added by Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
