#!/bin/bash
export PS1="\[\e[0;31m\]\D{%F %T}|\[\e[1;33m\]\u|\[\e[36m\]\w$"

SYSTEM=`uname -s`
if [ $SYSTEM == "Darwin" ]; then
    [[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
    [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
    if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
        . /opt/local/etc/profile.d/bash_completion.sh
    fi
fi
if [ $SYSTEM == "Linux" ]; then
    [ -f /usr/share/autojump/autojump.sh ] && source /usr/share/autojump/autojump.sh
    [ -f /etc/bash_completion ] && source /etc/bash_completion
    [ -f ~/.local/bin/virtualenvwrapper-setting.sh ] && source ~/.local/bin/virtualenvwrapper-setting.sh
    # bind '"\e[A": history-search-backward'
    #  bind '"\e[B": history-search-forward'
    #    /usr/bin/setxkbmap -option "ctrl:nocaps"
    #    iwconfig wlp0s20f3 power off
fi

#添加git的自动完成命令功能
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function


if [ -f ~/.aliasrc ]; then
    source ~/.aliasrc
fi

ulimit -c unlimited

#if [ -f ~/.fzf.bash ]; then
#    source ~/.fzf.bash
#fi

#添加git的自动完成命令功能
if [ -f ~/.path.bash ]; then
    source ~/.path.bash
fi
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export EDITOR=nvim

